### ISSUE TITLE
Instrumentalização do projeto

### ISSUE THREAD

**Issue by patymori** [scieloorg/catalogmanager#76]
Criar meios para:

- Registro de Log
- Prometheus/Grafana
- StatsD
- Sentry

Sub-tarefas:

- [x] #102 Implementação de logging na aplicação
- [x] #103 Configuração e testes do sistema de logs da aplicação
- [x] #109 Implementar as métricas com o Prometheus
